export const FETCH_CHARACTERS_REQUEST = 'FETCH_CHARACTERS_REQUEST';
export const FETCH_CHARACTERS_SUCCESS = 'FETCH_CHARACTERS_SUCCESS';
export const FETCH_CHARACTERS_FAILURE = 'FETCH_CHARACTERS_FAILURE';

export const SET_ITEMS_PER_PAGE = 'SET_ITEMS_PER_PAGE';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_TOTAL_CHARACTERS = 'SET_TOTAL_CHARACTERS';
export const SEARCH_CHARACTERS = 'SEARCH_CHARACTERS';

export const SET_SORT_ORDER = 'SET_SORT_ORDER';
export const SORT_CHARACTERS = 'SORT_CHARACTERS';
